### ISSUE TITLE
Bug in component generator

### ISSUE THREAD

**Issue by justinsuen** [davidhu2000/react_redux_generator#1]
1. The `props` in the following should be `state` instead. Maybe you can even have `(state, ownProps)`.
```
const mapStateToProps = props => ({
});
```

2. Also, it needs to `export default` in
```
export connect(
  mapStateToProps,
  mapDispatchToProps
)(Component);
```

**Comment by justinsuen** [comment]
I see you fixed the default already HAHA... I should reinstall on npm. What do you think about 1. though?

**Comment by davidhu2000** [comment]
I agree. And the update is live.
